version: '3.8'

services:

  nomenclature-service:
    build:
      context: ./WMS.NomenclatureService
      dockerfile: Dockerfile
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=wms-db;Port=5432;Database=wms-db;Username=postgres;Password=wmsPassword"
    ports:
      - "8000:80"
    networks:
      - wms-network
    depends_on:
      - wms-db

  employee-service:
    build:
      context: ./WMS.EmployeeService
      dockerfile: Dockerfile
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=employee-db;Port=5432;Database=employee-db;Username=postgres;Password=employeePassword"
    ports:
      - "8010:80"
    networks:
      - wms-network
    depends_on:
      - employee-db

  wms-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wmsPassword
      POSTGRES_DB: wms-db
    volumes:
      - wms-db:/var/lib/postgresql/data
    ports:
      - "5400:5432"
    networks:
      - wms-network
    command: "-c log_statement=all"

  employee-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: employeePassword
      POSTGRES_DB: employee-db
    volumes:
      - employee-db:/var/lib/postgresql/data
    ports:
      - "5410:5432"
    networks:
      - wms-network
    command: "-c log_statement=all"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - wms-network

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - wms-network

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - wms-network

networks:
  wms-network:
    driver: bridge

volumes:
  wms-volume:
    driver: local
  nomenclature-service:
    driver: local
  employee-service:
    driver: local
  wms-db:
    driver: local
  employee-db:
    driver: local
